import type { ColorMode, PaletteId, PaletteMeta, SemanticColors } from "./types";

export const palettes: Record<PaletteId, Record<ColorMode, SemanticColors>> = {
	neutral: {
		light: {
			background: "#F7F7F5",
			surface: "#FFFFFF",
			surfaceMuted: "#EEEEEC",
			text: "#1A1A18",
			textMuted: "#6B6B66",
			border: "#E2E2DE",
			primary: "#2C2C28",
			primaryForeground: "#FAFAF8",
			accent: "#5C5C56",
			danger: "#C0392B",
			success: "#2D7A4F",
		},
		dark: {
			background: "#121211",
			surface: "#1C1C1A",
			surfaceMuted: "#262624",
			text: "#F2F2EE",
			textMuted: "#A3A39C",
			border: "#333330",
			primary: "#E8E8E2",
			primaryForeground: "#161614",
			accent: "#C4C4BC",
			danger: "#E57373",
			success: "#6BCB8B",
		},
	},
	ocean: {
		light: {
			background: "#F4F8FC",
			surface: "#FFFFFF",
			surfaceMuted: "#E8F1F8",
			text: "#0F2438",
			textMuted: "#4A6A84",
			border: "#D0E0EE",
			primary: "#1B6CA8",
			primaryForeground: "#FFFFFF",
			accent: "#0E8FBF",
			danger: "#C0392B",
			success: "#1F8A70",
		},
		dark: {
			background: "#0B1620",
			surface: "#132230",
			surfaceMuted: "#1A3144",
			text: "#E8F2FA",
			textMuted: "#8AA8C0",
			border: "#243A50",
			primary: "#4BA3DB",
			primaryForeground: "#071018",
			accent: "#3DCFE8",
			danger: "#EF7A72",
			success: "#4ECD9A",
		},
	},
	forest: {
		light: {
			background: "#F4F8F4",
			surface: "#FFFFFF",
			surfaceMuted: "#E6F0E6",
			text: "#142018",
			textMuted: "#4A6350",
			border: "#D0E0D2",
			primary: "#2D6A4F",
			primaryForeground: "#FFFFFF",
			accent: "#40916C",
			danger: "#C0392B",
			success: "#2D6A4F",
		},
		dark: {
			background: "#0E1610",
			surface: "#16201A",
			surfaceMuted: "#1E2C22",
			text: "#E8F2EA",
			textMuted: "#8AAB94",
			border: "#2A3C30",
			primary: "#6BCB8B",
			primaryForeground: "#0A140C",
			accent: "#95D5B2",
			danger: "#EF7A72",
			success: "#6BCB8B",
		},
	},
	violet: {
		light: {
			background: "#F7F5FB",
			surface: "#FFFFFF",
			surfaceMuted: "#EEE8F6",
			text: "#1C1428",
			textMuted: "#64567A",
			border: "#E0D6EE",
			primary: "#6B3FA0",
			primaryForeground: "#FFFFFF",
			accent: "#8B5CF6",
			danger: "#C0392B",
			success: "#2D7A4F",
		},
		dark: {
			background: "#120E18",
			surface: "#1C1626",
			surfaceMuted: "#271E34",
			text: "#F0EAF8",
			textMuted: "#A894C0",
			border: "#352A44",
			primary: "#B794F6",
			primaryForeground: "#120E18",
			accent: "#C4B5FD",
			danger: "#EF7A72",
			success: "#6BCB8B",
		},
	},
};

export const PALETTE_META: PaletteMeta[] = [
	{ id: "neutral", label: "Neutral", description: "Warm gray" },
	{ id: "ocean", label: "Ocean", description: "Bluish" },
	{ id: "forest", label: "Forest", description: "Greenish" },
	{ id: "violet", label: "Violet", description: "Purple" },
];

export const APPEARANCE_OPTIONS: { id: import("./types").Appearance; label: string }[] = [
	{ id: "light", label: "Light" },
	{ id: "dark", label: "Dark" },
	{ id: "system", label: "System" },
];
